
// Questions Database
const questions = {
    "English": {
        "Easy": [
            { word: "CAT", hints: ["Pet animal", "Says meow", "Likes milk"] },
            { word: "DOG", hints: ["Barks", "Wags tail", "Best friend"] },
            { word: "HAT", hints: ["Wear on head", "Keeps warm", "Like a cap"] },
            { word: "BED", hints: ["Sleep here", "In bedroom", "Rest place"] },
            { word: "SUN", hints: ["In sky", "Very hot", "Gives light"] },
            { word: "BOX", hints: ["Put things in", "Has lid", "Container"] },
            { word: "PEN", hints: ["Write with it", "Has ink", "Not pencil"] },
            { word: "BAG", hints: ["Carry things", "Has handle", "Hold items"] },
            { word: "CUP", hints: ["Drink from it", "Hold liquid", "Like glass"] },
            { word: "MAP", hints: ["Shows places", "For direction", "Like guide"] },
            { word: "KEY", hints: ["Opens locks", "Metal tool", "For doors"] },
            { word: "BUS", hints: ["Big vehicle", "Many seats", "Public transport"] },
            { word: "ICE", hints: ["Very cold", "Frozen water", "In drinks"] },
            { word: "EGG", hints: ["From birds", "For breakfast", "Shell outside"] },
            { word: "ANT", hints: ["Small insect", "Works hard", "In group"] },
            { word: "TOY", hints: ["Play with it", "For fun", "For kids"] },
            { word: "FAN", hints: ["Makes wind", "Keeps cool", "Spins around"] },
            { word: "CAR", hints: ["Has wheels", "For driving", "On road"] },
            { word: "DAY", hints: ["Not night", "Sun time", "Wake time"] },
            { word: "JAM", hints: ["Sweet spread", "On bread", "From fruit"] }
        ],
        "Medium": [
            { word: "WRITE", hints: ["Use pen", "Make words", "On paper"] },
            { word: "STORY", hints: ["Has plot", "With characters", "Like a tale"] },
            { word: "SPEAK", hints: ["Use voice", "Make words", "Talk out"] },
            { word: "PHONE", hints: ["Call others", "Communication", "Device"] },
            { word: "CLOCK", hints: ["Shows time", "Has hands", "On wall"] },
            { word: "BREAD", hints: ["Baked food", "For sandwich", "From flour"] },
            { word: "PLANT", hints: ["Grows in soil", "Needs water", "Has leaves"] },
            { word: "SMILE", hints: ["Happy face", "Show joy", "With lips"] },
            { word: "MUSIC", hints: ["Listen to", "Has rhythm", "Makes sound"] },
            { word: "BEACH", hints: ["By ocean", "Has sand", "For swimming"] },
            { word: "CLOUD", hints: ["In sky", "Makes rain", "White puff"] },
            { word: "HOUSE", hints: ["Live in it", "Has rooms", "Building"] },
            { word: "PAPER", hints: ["Write on it", "Thin sheet", "From trees"] },
            { word: "WATER", hints: ["Drink it", "Clear liquid", "From tap"] },
            { word: "CHAIR", hints: ["Sit on it", "Furniture", "At desk"] },
            { word: "SLEEP", hints: ["At night", "Close eyes", "Rest time"] },
            { word: "GRASS", hints: ["Green plant", "In yard", "Needs cutting"] },
            { word: "TRAIN", hints: ["On tracks", "Long vehicle", "Many cars"] },
            { word: "LIGHT", hints: ["Not dark", "Brightness", "From bulb"] },
            { word: "FRUIT", hints: ["To eat", "Sweet food", "From trees"] }
        ],
        "Hard": [
            { word: "METAPHOR", hints: ["Figure of speech", "Indirect comparison", "Literary device"] },
            { word: "SYLLABLE", hints: ["Word part", "Sound unit", "Speech segment"] },
            { word: "GRAMMAR", hints: ["Language rules", "Sentence structure", "Writing guide"] },
            { word: "ADJECTIVE", hints: ["Describes nouns", "Modifies words", "Like 'happy', 'big'"] },
            { word: "NARRATIVE", hints: ["Story form", "Tale telling", "Plot sequence"] },
            { word: "THESAURUS", hints: ["Word book", "Synonym finder", "Language tool"] },
            { word: "CONSONANT", hints: ["Letter type", "Not vowel", "Speech sound"] },
            { word: "PARAGRAPH", hints: ["Text section", "Related sentences", "Writing block"] },
            { word: "QUOTATION", hints: ["Exact words", "Speech marks", "Direct saying"] },
            { word: "PRONOUN", hints: ["Replaces noun", "Like 'he', 'she'", "Person word"] },
            { word: "VOCABULARY", hints: ["Word knowledge", "Language set", "Term collection"] },
            { word: "LITERATURE", hints: ["Written works", "Books collection", "Reading material"] },
            { word: "PREPOSITION", hints: ["Position word", "Like 'in', 'on'", "Place relation"] },
            { word: "CONJUNCTION", hints: ["Joining word", "Connects parts", "Like 'and', 'but'"] },
            { word: "APOSTROPHE", hints: ["Punctuation mark", "Shows possession", "Contraction sign"] },
            { word: "HOMOPHONE", hints: ["Same sound", "Different spelling", "Like 'there', 'their'"] },
            { word: "SYNONYM", hints: ["Similar meaning", "Word match", "Like 'big', 'large'"] },
            { word: "ANTONYM", hints: ["Opposite word", "Contrary meaning", "Like 'hot', 'cold'"] },
            { word: "ALLITERATION", hints: ["Same sound start", "Repeated consonant", "Like 'Peter Piper'"] },
            { word: "ONOMATOPOEIA", hints: ["Sound word", "Like 'buzz', 'pop'", "Noise spelling"] }
        ]
    },
    "Math": {
        "Easy": [
            { word: "ADD", hints: ["Plus sign", "Make more", "Combine"] },
            { word: "TWO", hints: ["After one", "Before three", "Pair number"] },
            { word: "ONE", hints: ["First number", "Single unit", "Alone"] },
            { word: "SUM", hints: ["Add result", "Total", "Combined"] },
            { word: "TEN", hints: ["After nine", "Two hands", "Base number"] },
            { word: "HALF", hints: ["Split in two", "Equal parts", "Divide"] },
            { word: "LESS", hints: ["Not as much", "Smaller", "Minus"] },
            { word: "MORE", hints: ["Extra amount", "Added", "Greater"] },
            { word: "LINE", hints: ["Straight path", "With ruler", "Point to point"] },
            { word: "ZERO", hints: ["Nothing", "No value", "Empty"] },
            { word: "FIVE", hints: ["One hand", "Before six", "After four"] },
            { word: "FOUR", hints: ["After three", "Before five", "Car wheels"] },
            { word: "PLUS", hints: ["Add sign", "Increase", "More than"] },
            { word: "CUBE", hints: ["Box shape", "Six sides", "Equal edges"] },
            { word: "OVAL", hints: ["Egg shape", "Round form", "Not circle"] },
            { word: "PAIR", hints: ["Group of two", "Doubles", "Matching"] },
            { word: "INCH", hints: ["Small length", "Measure", "Ruler unit"] },
            { word: "SIDE", hints: ["Edge part", "Border", "Shape part"] },
            { word: "AREA", hints: ["Space inside", "Coverage", "Surface"] },
            { word: "TIME", hints: ["Clock shows", "Hours pass", "Minutes"] }
        ],
        "Medium": [
            { word: "DIVIDE", hints: ["Split up", "Share equal", "Division"] },
            { word: "SQUARE", hints: ["Four sides", "Equal sides", "Shape"] },
            { word: "CIRCLE", hints: ["Round shape", "No corners", "360 degrees"] },
            { word: "ANGLE", hints: ["Corner measure", "Degrees", "Point meet"] },
            { word: "GRAPH", hints: ["Show data", "Plot points", "Visual math"] },
            { word: "MINUS", hints: ["Take away", "Subtract", "Reduce"] },
            { word: "TIMES", hints: ["Multiply", "Groups of", "Repeated add"] },
            { word: "EQUAL", hints: ["Same value", "Balance", "Fair share"] },
            { word: "WHOLE", hints: ["Complete", "Not fraction", "Full amount"] },
            { word: "DIGIT", hints: ["Single number", "0 to 9", "Number symbol"] },
            { word: "DOZEN", hints: ["Twelve items", "Group count", "Baker's unit"] },
            { word: "METER", hints: ["Length unit", "100 cm", "Measure"] },
            { word: "VOLUME", hints: ["Space inside", "Container size", "3D measure"] },
            { word: "FACTOR", hints: ["Divides into", "Number part", "Multiple"] },
            { word: "PRIME", hints: ["Special number", "Two factors", "Like 2,3,5"] },
            { word: "RATIO", hints: ["Compare size", "Proportion", "Relationship"] },
            { word: "SCALE", hints: ["Size compare", "Measure tool", "Map guide"] },
            { word: "WIDTH", hints: ["Side to side", "Broad measure", "How wide"] },
            { word: "DEPTH", hints: ["How deep", "Top to bottom", "Third dimension"] },
            { word: "COUNT", hints: ["How many", "Number of", "Tally up"] }
        ],
        "Hard": [
            { word: "GEOMETRY", hints: ["Shape study", "Space math", "Angles and lines"] },
            { word: "EQUATION", hints: ["Math sentence", "Equal parts", "Problem solve"] },
            { word: "FRACTION", hints: ["Part whole", "Division show", "Like 1/2"] },
            { word: "DECIMAL", hints: ["Point number", "Base ten", "Like 0.5"] },
            { word: "PERIMETER", hints: ["Outside measure", "Border length", "Around shape"] },
            { word: "DIAMETER", hints: ["Circle width", "Through center", "Longest line"] },
            { word: "PARALLEL", hints: ["Never meet", "Same distance", "Equal space"] },
            { word: "CYLINDER", hints: ["Tube shape", "Round sides", "Like can"] },
            { word: "TRIANGLE", hints: ["Three angles", "Three sides", "Basic shape"] },
            { word: "QUADRATIC", hints: ["Square term", "x squared", "Curve graph"] },
            { word: "SYMMETRY", hints: ["Mirror image", "Equal parts", "Balance line"] },
            { word: "COORDINATE", hints: ["Point location", "Grid position", "x,y value"] },
            { word: "POLYNOMIAL", hints: ["Many terms", "Math expression", "Variable power"] },
            { word: "PROPORTION", hints: ["Equal ratios", "Same relation", "Size compare"] },
            { word: "ALGORITHM", hints: ["Step process", "Problem solve", "Math method"] },
            { word: "HYPOTENUSE", hints: ["Longest side", "Right triangle", "Square root"] },
            { word: "LOGARITHM", hints: ["Power math", "Exponent solve", "Base number"] },
            { word: "COEFFICIENT", hints: ["Number part", "Term multiply", "Variable factor"] },
            { word: "DENOMINATOR", hints: ["Fraction bottom", "Division under", "Divide by"] },
            { word: "PROBABILITY", hints: ["Chance study", "Likely hood", "Outcome math"] }
        ]
    },
    "Science": {
        "Easy": [
            { word: "AIR", hints: ["We breathe", "Invisible", "In wind"] },
            { word: "SUN", hints: ["Sky light", "Very hot", "Day star"] },
            { word: "RAIN", hints: ["Water drops", "From clouds", "Wet weather"] },
            { word: "HEAT", hints: ["Makes warm", "Temperature", "Not cold"] },
            { word: "LEAF", hints: ["Plant part", "Tree part", "Green color"] },
            { word: "SEED", hints: ["Plant start", "Grows new", "In fruit"] },
            { word: "ROCK", hints: ["Hard stone", "Ground part", "Earth piece"] },
            { word: "SOIL", hints: ["Plants grow", "Earth cover", "Dirt ground"] },
            { word: "MOON", hints: ["Night light", "Sky object", "Earth friend"] },
            { word: "STAR", hints: ["Sky light", "Night shine", "Space point"] },
            { word: "FISH", hints: ["Swims", "Water pet", "Has fins"] },
            { word: "BIRD", hints: ["Can fly", "Has wings", "Makes nest"] },
            { word: "TREE", hints: ["Big plant", "Has leaves", "Gives shade"] },
            { word: "WIND", hints: ["Moving air", "Feel blow", "Makes cool"] },
            { word: "SNOW", hints: ["White fall", "Cold time", "Ice crystal"] },
            { word: "FROG", hints: ["Jumps high", "Lives wet", "Says ribbit"] },
            { word: "BEAR", hints: ["Big animal", "Forest life", "Likes honey"] },
            { word: "CLOUD", hints: ["Sky float", "Rain maker", "White puff"] },
            { word: "BONE", hints: ["Body part", "Hard part", "Skeleton"] },
            { word: "FOOD", hints: ["We eat", "Gives energy", "For life"] }
        ],
        "Medium": [
            { word: "PLANT", hints: ["Grows in soil", "Makes food", "Needs water"] },
            { word: "WATER", hints: ["Liquid form", "H2O", "For drink"] },
            { word: "EARTH", hints: ["Our planet", "Has life", "Blue world"] },
            { word: "SPACE", hints: ["Stars here", "Above sky", "Planets move"] },
            { word: "SOUND", hints: ["We hear", "Makes waves", "Travels air"] },
            { word: "LIGHT", hints: ["Helps see", "Travels fast", "From sun"] },
            { word: "FORCE", hints: ["Push pull", "Makes move", "Has strength"] },
            { word: "METAL", hints: ["Hard material", "Conducts heat", "Like iron"] },
            { word: "SOLID", hints: ["Firm state", "Keeps shape", "Not liquid"] },
            { word: "BRAIN", hints: ["Think organ", "Head part", "Controls body"] },
            { word: "HEART", hints: ["Pumps blood", "Vital organ", "Never stops"] },
            { word: "BLOOD", hints: ["Red fluid", "In veins", "Carries oxygen"] },
            { word: "STORM", hints: ["Strong weather", "Lightning rain", "Wind power"] },
            { word: "OCEAN", hints: ["Big water", "Salt water", "Has waves"] },
            { word: "MAGNET", hints: ["Pulls metal", "Has poles", "Attracts iron"] },
            { word: "ENERGY", hints: ["Power form", "Makes work", "Gives force"] },
            { word: "PLANET", hints: ["Space body", "Orbits sun", "Like Earth"] },
            { word: "INSECT", hints: ["Small bug", "Six legs", "Has wings"] },
            { word: "MUSCLE", hints: ["Body mover", "Gets strong", "Under skin"] },
            { word: "CARBON", hints: ["In diamond", "Life element", "Makes chains"] }
        ],
        "Hard": [
            { word: "MOLECULE", hints: ["Atom group", "Matter unit", "Chemical part"] },
            { word: "ELECTRON", hints: ["Atom part", "Negative charge", "Orbits nucleus"] },
            { word: "GRAVITY", hints: ["Pulls down", "Earth force", "Space effect"] },
            { word: "CHEMISTRY", hints: ["Matter study", "Reactions", "Elements mix"] },
            { word: "EVOLUTION", hints: ["Life change", "Species adapt", "Darwin theory"] },
            { word: "ECOSYSTEM", hints: ["Life system", "Nature balance", "Species home"] },
            { word: "RADIATION", hints: ["Energy wave", "Light form", "Heat transfer"] },
            { word: "ATMOSPHERE", hints: ["Air layer", "Earth cover", "Gas blanket"] },
            { word: "CHROMOSOME", hints: ["Gene carrier", "DNA part", "Cell thread"] },
            { word: "PHOTOSYNTHESIS", hints: ["Plant food", "Sun energy", "Leaf process"] },
            { word: "TEMPERATURE", hints: ["Heat measure", "How hot", "Degree scale"] },
            { word: "MICROSCOPE", hints: ["See small", "Science tool", "Makes bigger"] },
            { word: "HYPOTHESIS", hints: ["Test guess", "Science question", "Research start"] },
            { word: "LABORATORY", hints: ["Science room", "Test place", "Research space"] },
            { word: "EXPERIMENT", hints: ["Science test", "Try method", "Research way"] },
            { word: "CONSERVATION", hints: ["Save nature", "Keep safe", "Protect resource"] },
            { word: "METABOLISM", hints: ["Body process", "Life chemical", "Energy use"] },
            { word: "VERTEBRATE", hints: ["Has backbone", "Animal type", "Like mammals"] },
            { word: "INVERTEBRATE", hints: ["No backbone", "Animal type", "Like insects"] },
            { word: "PRECIPITATION", hints: ["Rain snow", "Water cycle", "Falls down"] }
        ]
    },
    "History": {
        "Easy": [
            { word: "WAR", hints: ["Big fight", "Conflict", "Battle"] },
            { word: "KING", hints: ["Male ruler", "Crown wear", "Palace live"] },
            { word: "SHIP", hints: ["Ocean boat", "Sea travel", "Water ride"] },
            { word: "GOLD", hints: ["Yellow metal", "Precious", "Treasure"] },
            { word: "CAVE", hints: ["Rock home", "Old shelter", "In mountain"] },
            { word: "TOOL", hints: ["Help work", "Make things", "Hand use"] },
            { word: "FARM", hints: ["Grow food", "Has animals", "Country place"] },
            { word: "FORT", hints: ["Strong wall", "Defense place", "Safe spot"] },
            { word: "CITY", hints: ["Big town", "Many people", "Urban place"] },
            { word: "FLAG", hints: ["Country sign", "On pole", "Nation mark"] },
            { word: "ARMY", hints: ["Soldiers group", "Military", "Fight force"] },
            { word: "TOMB", hints: ["Burial place", "Rest place", "Memory spot"] },
            { word: "CLAN", hints: ["Family group", "Tribe part", "Related all"] },
            { word: "ROME", hints: ["Old city", "Italy place", "Caesar home"] },
            { word: "WALL", hints: ["Defense build", "Keeps safe", "Barrier"] },
            { word: "BOAT", hints: ["Water ride", "Float thing", "River use"] },
            { word: "TENT", hints: ["Camp home", "Cloth house", "Travel stay"] },
            { word: "COIN", hints: ["Money piece", "Metal pay", "Round flat"] },
            { word: "FOOD", hints: ["To eat", "For life", "Makes full"] },
            { word: "TOWN", hints: ["Small city", "People live", "Has shops"] }
        ],
        "Medium": [
            { word: "CASTLE", hints: ["Stone building", "King's home", "Has towers"] },
            { word: "BATTLE", hints: ["War fight", "Army clash", "Conflict time"] },
            { word: "VIKING", hints: ["Norse sailor", "Ship warrior", "North people"] },
            { word: "EMPIRE", hints: ["Many lands", "Big kingdom", "Ruler control"] },
            { word: "PALACE", hints: ["Royal home", "Big house", "Rich place"] },
            { word: "KNIGHT", hints: ["Horse warrior", "Armor wear", "Sword fight"] },
            { word: "TEMPLE", hints: ["Holy place", "Worship spot", "Prayer house"] },
            { word: "PIRATE", hints: ["Sea robber", "Ship thief", "Ocean bad"] },
            { word: "COLONY", hints: ["New land", "Far settle", "From home"] },
            { word: "SHIELD", hints: ["War protect", "Block hits", "Defense tool"] },
            { word: "SWORD", hints: ["War weapon", "Metal blade", "Knight tool"] },
            { word: "TRADE", hints: ["Buy sell", "Exchange goods", "Business"] },
            { word: "QUEEN", hints: ["Lady ruler", "King's wife", "Crown woman"] },
            { word: "TRIBE", hints: ["People group", "Same culture", "Live together"] },
            { word: "SPEAR", hints: ["Long weapon", "Hunt tool", "Throw stick"] },
            { word: "CROWN", hints: ["King's hat", "Royal sign", "Power mark"] },
            { word: "SLAVE", hints: ["Forced work", "Not free", "Owned person"] },
            { word: "PEACE", hints: ["No war", "Calm time", "Friend state"] },
            { word: "ARMOR", hints: ["War clothes", "Metal suit", "Body guard"] },
            { word: "COURT", hints: ["King's room", "Judge place", "Royal meet"] }
        ],
        "Hard": [
            { word: "DEMOCRACY", hints: ["People rule", "Vote system", "Free choice"] },
            { word: "REVOLUTION", hints: ["Big change", "Power shift", "System flip"] },
            { word: "CIVILIZATION", hints: ["Culture group", "Advanced society", "People progress"] },
            { word: "ARCHAEOLOGY", hints: ["Study past", "Dig history", "Find old"] },
            { word: "MONARCHY", hints: ["King rule", "Royal power", "Crown system"] },
            { word: "RENAISSANCE", hints: ["Art rebirth", "Culture bloom", "Europe change"] },
            { word: "INDUSTRIAL", hints: ["Factory age", "Machine time", "Work change"] },
            { word: "COLONIALISM", hints: ["Take lands", "Rule far", "Empire build"] },
            { word: "DIPLOMACY", hints: ["Nation talk", "Peace work", "Country deals"] },
            { word: "FEUDALISM", hints: ["Land system", "Lord peasant", "Middle age"] },
            { word: "MIGRATION", hints: ["People move", "Change home", "Travel live"] },
            { word: "CRUSADES", hints: ["Holy wars", "Church fight", "Middle ages"] },
            { word: "REFORMATION", hints: ["Church change", "Belief shift", "Faith reform"] },
            { word: "IMPERIALISM", hints: ["Empire grow", "Power spread", "Nation control"] },
            { word: "ARISTOCRAT", hints: ["Noble birth", "High class", "Rich power"] },
            { word: "PARLIAMENT", hints: ["Law makers", "People voice", "Government group"] },
            { word: "EXPEDITION", hints: ["Journey group", "Explore trip", "Discovery team"] },
            { word: "PROPAGANDA", hints: ["Control news", "Change minds", "Spread ideas"] },
            { word: "DYNASTY", hints: ["Family rule", "Power line", "Time kings"] },
            { word: "ALLIANCE", hints: ["Team nations", "Work together", "Help group"] }
        ]
    },
    "Arts": {
        "Easy": [
            { word: "ART", hints: ["Make pretty", "Draw paint", "Create thing"] },
            { word: "RED", hints: ["Hot color", "Like fire", "Stop light"] },
            { word: "BLUE", hints: ["Sky color", "Sea color", "Cool shade"] },
            { word: "DRAW", hints: ["Make lines", "Use pencil", "Create picture"] },
            { word: "SING", hints: ["Make music", "Use voice", "Like bird"] },
            { word: "DRUM", hints: ["Hit music", "Make beat", "Loud sound"] },
            { word: "CLAY", hints: ["Soft stuff", "Make pots", "Earth art"] },
            { word: "PAINT", hints: ["Color art", "Use brush", "Make picture"] },
            { word: "SONG", hints: ["Music piece", "Has words", "Can sing"] },
            { word: "DANCE", hints: ["Move body", "With music", "Like fun"] },
            { word: "LINE", hints: ["Draw mark", "Straight path", "Basic art"] },
            { word: "BAND", hints: ["Music group", "Play songs", "Make sound"] },
            { word: "PLAY", hints: ["Act story", "Stage show", "Fun time"] },
            { word: "TUNE", hints: ["Song part", "Nice sound", "Music piece"] },
            { word: "MASK", hints: ["Face cover", "Hide look", "Drama use"] },
            { word: "FILM", hints: ["Movie show", "Screen play", "Watch story"] },
            { word: "POSE", hints: ["Hold still", "Model stand", "Picture time"] },
            { word: "PROP", hints: ["Stage thing", "Show item", "Actor use"] },
            { word: "BEAT", hints: ["Music pulse", "Drum sound", "Time keep"] },
            { word: "TONE", hints: ["Sound type", "Color shade", "Voice way"] }
        ],
        "Medium": [
            { word: "MUSIC", hints: ["Sound art", "Listen joy", "Note song"] },
            { word: "COLOR", hints: ["Paint type", "See shade", "Art part"] },
            { word: "STAGE", hints: ["Show place", "Actor space", "Performance"] },
            { word: "BRUSH", hints: ["Paint tool", "Art stick", "Color spread"] },
            { word: "DANCE", hints: ["Move art", "Body flow", "Music move"] },
            { word: "DRAMA", hints: ["Act story", "Stage show", "Theater art"] },
            { word: "SCENE", hints: ["Play part", "Story piece", "Action spot"] },
            { word: "CHOIR", hints: ["Sing group", "Voice team", "Music bunch"] },
            { word: "PIANO", hints: ["Key music", "Note play", "Sound board"] },
            { word: "FLUTE", hints: ["Wind music", "Blow pipe", "High sound"] },
            { word: "PAINT", hints: ["Color art", "Make picture", "Brush use"] },
            { word: "CRAFT", hints: ["Make art", "Hand work", "Skill create"] },
            { word: "STYLE", hints: ["Art way", "Look type", "Create form"] },
            { word: "THEME", hints: ["Main idea", "Art focus", "Story base"] },
            { word: "BLEND", hints: ["Mix color", "Smooth change", "Combine art"] },
            { word: "FRAME", hints: ["Picture edge", "Art border", "Hold work"] },
            { word: "RHYTHM", hints: ["Beat flow", "Time pattern", "Music move"] },
            { word: "SKETCH", hints: ["Quick draw", "Plan art", "Light lines"] },
            { word: "VOICE", hints: ["Sound make", "Sing tool", "Talk sound"] },
            { word: "DANCE", hints: ["Move show", "Body art", "Music flow"] }
        ],
        "Hard": [
            { word: "SCULPTURE", hints: ["3D art", "Shape form", "Carved work"] },
            { word: "ORCHESTRA", hints: ["Music group", "Many players", "Classic sound"] },
            { word: "SYMPHONY", hints: ["Big music", "Full sound", "Many parts"] },
            { word: "ABSTRACT", hints: ["Not real", "Free form", "Mind art"] },
            { word: "COMPOSITION", hints: ["Art arrange", "Part place", "Work order"] },
            { word: "TECHNIQUE", hints: ["Skill way", "Method use", "How done"] },
            { word: "PERSPECTIVE", hints: ["View point", "See depth", "Space show"] },
            { word: "EXHIBITION", hints: ["Art show", "Work display", "Gallery time"] },
            { word: "MASTERPIECE", hints: ["Best work", "Great art", "Top create"] },
            { word: "RENAISSANCE", hints: ["Art time", "Culture new", "Style change"] },
            { word: "SURREALISM", hints: ["Dream art", "Strange real", "Mind view"] },
            { word: "MINIMALISM", hints: ["Simple art", "Less more", "Clean style"] },
            { word: "CLASSICAL", hints: ["Old style", "Time test", "Pure form"] },
            { word: "HARMONY", hints: ["Good mix", "Nice blend", "Sweet sound"] },
            { word: "IMPROVISE", hints: ["Make new", "No plan", "Free create"] },
            { word: "CHOREOGRAPHY", hints: ["Dance plan", "Move design", "Step make"] },
            { word: "INSTALLATION", hints: ["Space art", "Place work", "Site show"] },
            { word: "PERFORMANCE", hints: ["Live show", "Act time", "Stage work"] },
            { word: "EXPRESSIONISM", hints: ["Feel art", "Emotion show", "Inner view"] },
            { word: "ILLUSTRATION", hints: ["Book art", "Story show", "Picture tell"] }
        ]
    }
};

// Configuration for different difficulty levels
const gameConfig = {
    timeLimit: {
        Easy: 20,
        Medium: 15,
        Hard: 8
    },
    pointsPerQuestion: {
        Easy: 10,
        Medium: 15,
        Hard: 20
    },
    targetScore: {
        Easy: 150,
        Medium: 225,
        Hard: 300
    }
}; 